name: Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    paths:
      - '.github/workflows/build.yml'
      - 'c2a-aocs/CMakeLists.txt'
      - 'c2a-aocs/src/**'

env:
  S2E_AOBC_VERSION: v2.0.1

jobs:
  build_s2e_win:
    name: Build with S2E on Windows VS2022
    # VS2022 を使うため
    runs-on: windows-2022
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: checkout the submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: checkout S2E AOBC
        uses: actions/checkout@v3
        with:
          path: s2e-aobc
          repository: ut-issl/s2e-aobc
          ref: '${{ env.S2E_AOBC_VERSION }}'
          submodules: recursive
          ssh-key: ${{ secrets.S2E_AOBC_SSH_KEY }}
          fetch-depth: 1

      - name: Configure build for x86
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64_x86

      - name: show tools version
        shell: powershell
        run: |
          cmake --version

      - name: cache extlib
        id: cache-extlib
        uses: actions/cache@v3
        with:
          key: extlib-${{ runner.os }}-${{ hashFiles('./s2e-aobc/s2e-core/ExtLibraries/**') }}
          path: ExtLibraries

      - name: build extlib
        if: steps.cache-extlib.outputs.cache-hit != 'true'
        shell: powershell
        working-directory: ./s2e-aobc/s2e-core/ExtLibraries
        run: |
          cmake -G "Visual Studio 17 2022" -A Win32 -DCMAKE_CONFIGURATION_TYPES:STRING="Debug"
          cmake --build .

      - name: install extlib
        if: steps.cache-extlib.outputs.cache-hit != 'true'
        shell: powershell
        working-directory: ./s2e-aobc/s2e-core/ExtLibraries
        run: |
          cmake --install .

      - name: check extlib
        shell: powershell
        working-directory: ./s2e-aobc/ExtLibraries
        run: |
          ls cspice
          ls cspice/cspice_msvs/lib
          ls cspice/include
          ls cspice/generic_kernels
          ls nrlmsise00
          ls nrlmsise00/table
          ls nrlmsise00/lib
          ls nrlmsise00/lib/libnrlmsise00.lib
          ls nrlmsise00/src

      - name: build
        shell: cmd
        working-directory: ./s2e-aobc/s2e-aocs-core
        run: |
          cl.exe
          cmake -G "Visual Studio 17 2022" -A Win32 -DCMAKE_CONFIGURATION_TYPES:STRING="Debug" -DFLIGHT_SW_DIR=../../../ -DC2A_NAME=c2a-aobc -DUSE_C2A=ON
          cmake --build .
